/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.pi.basepi;

/**
 *
 * @author athyla
 */
public class AtualizarPedido extends javax.swing.JFrame {

    /**
     * Creates new form DetalhePedido
     */
    public AtualizarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlAtualizarPedido = new javax.swing.JPanel();
        lblAtualizarPedido = new javax.swing.JLabel();
        lblApVendedor = new javax.swing.JLabel();
        lblApCliente = new javax.swing.JLabel();
        txtApDtPedido = new javax.swing.JFormattedTextField();
        lblApCpfCliente = new javax.swing.JLabel();
        lblApDtPedido = new javax.swing.JLabel();
        lblApValorTotal = new javax.swing.JLabel();
        txtApVendedor = new javax.swing.JTextField();
        txtApCliente = new javax.swing.JTextField();
        txtApCpfCliente = new javax.swing.JFormattedTextField();
        txtApValorTotal = new javax.swing.JFormattedTextField();
        lblApProdutos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblApProdutos = new javax.swing.JTable();
        btnApVoltar = new javax.swing.JButton();
        btnApAtualizar = new javax.swing.JButton();
        txtApPesquisarProduto = new javax.swing.JTextField();
        btnApAdicionarProduto = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlAtualizarPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAtualizarPedido.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblAtualizarPedido.setText("Atualizar Pedido N°: ");

        javax.swing.GroupLayout pnlAtualizarPedidoLayout = new javax.swing.GroupLayout(pnlAtualizarPedido);
        pnlAtualizarPedido.setLayout(pnlAtualizarPedidoLayout);
        pnlAtualizarPedidoLayout.setHorizontalGroup(
            pnlAtualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtualizarPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAtualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(199, 199, 199))
        );
        pnlAtualizarPedidoLayout.setVerticalGroup(
            pnlAtualizarPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtualizarPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAtualizarPedido)
                .addContainerGap())
        );

        lblApVendedor.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApVendedor.setText("Vendedor:");

        lblApCliente.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApCliente.setText("Cliente:");

        try {
            txtApDtPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblApCpfCliente.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApCpfCliente.setText("CPF Cliente:");

        lblApDtPedido.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApDtPedido.setText("Dt do Pedido:");

        lblApValorTotal.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApValorTotal.setText("Valor Total:");

        try {
            txtApCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtApValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$###.###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblApProdutos.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblApProdutos.setText("Produtos:");

        tblApProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Marca", "Produto", "Qtd", "Preço Unitário"
            }
        ));
        jScrollPane2.setViewportView(tblApProdutos);

        btnApVoltar.setText("Voltar");
        btnApVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApVoltarActionPerformed(evt);
            }
        });

        btnApAtualizar.setText("Atualizar");
        btnApAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApAtualizarActionPerformed(evt);
            }
        });

        txtApPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApPesquisarProdutoActionPerformed(evt);
            }
        });

        btnApAdicionarProduto.setText("Adicionar Produto");
        btnApAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApAdicionarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAtualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblApCpfCliente)
                            .addComponent(lblApDtPedido)
                            .addComponent(lblApCliente)
                            .addComponent(lblApVendedor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblApProdutos)
                                .addComponent(lblApValorTotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApAdicionarProduto))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtApVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApCpfCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(txtApValorTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApDtPedido, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnApAtualizar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAtualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApVendedor)
                    .addComponent(txtApVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApCliente)
                    .addComponent(txtApCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApCpfCliente)
                    .addComponent(txtApCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApDtPedido)
                    .addComponent(txtApDtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApValorTotal)
                    .addComponent(txtApValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApAdicionarProduto))
                .addGap(5, 5, 5)
                .addComponent(lblApProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApVoltar)
                    .addComponent(btnApAtualizar))
                .addGap(161, 161, 161))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApAdicionarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApAdicionarProdutoActionPerformed

    private void txtApPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApPesquisarProdutoActionPerformed

    private void btnApVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnApVoltarActionPerformed

    private void btnApAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApAdicionarProduto;
    private javax.swing.JButton btnApAtualizar;
    private javax.swing.JButton btnApVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApCliente;
    private javax.swing.JLabel lblApCpfCliente;
    private javax.swing.JLabel lblApDtPedido;
    private javax.swing.JLabel lblApProdutos;
    private javax.swing.JLabel lblApValorTotal;
    private javax.swing.JLabel lblApVendedor;
    private javax.swing.JLabel lblAtualizarPedido;
    private javax.swing.JPanel pnlAtualizarPedido;
    private javax.swing.JTable tblApProdutos;
    private javax.swing.JTextField txtApCliente;
    private javax.swing.JFormattedTextField txtApCpfCliente;
    private javax.swing.JFormattedTextField txtApDtPedido;
    private javax.swing.JTextField txtApPesquisarProduto;
    private javax.swing.JFormattedTextField txtApValorTotal;
    private javax.swing.JTextField txtApVendedor;
    // End of variables declaration//GEN-END:variables
}
